name: java-status-check

on:
  push:
    paths:
      - '01-cache/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Prepare testing environment
        run: |
          cd 01-cache
          source aliases.sh
          docker-compose build
      - name: Run tests
        run: |
          cd 01-cache
          source aliases.sh
          ant test
