name: php-status-check

on:
  push:
    paths:
      - 'PHP/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: PHPUnit
        run: |
          cd PHP
          source aliases.sh
          composer install
          phpunit